[package]
name = "svraid_lookup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sv_raid_reader = {git = "https://github.com/SteveCookTU/sv_raid_reader.git", rev = "82433d1" }
ehttp = "0.2.0"
egui_extras = { version = "0.20.0", features = ['image']}
image = {version = "0.24.5", features = ['png']}

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3"
eframe = { version = "0.20.1", features = ['wgpu'] }

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"
eframe = "0.20.1"
wasm-bindgen-futures = "0.4.33"


[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2